version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.5-browsers # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install node_modules with npm
          command: npm install
      - run:
          name: Install puppeteer and karma-chrome-launcher
          command: npm i -D puppeteer karma-chrome-launcher
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run: 
          name: Build
          command: npm run build --prod 
          environment:
            CHROME_BIN: /usr/bin/chromium        
      - run: 
          name: Running unit tests with karma
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
          environment:
            CHROME_BIN: /usr/bin/chromium