version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.5-browsers # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: circleci-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install node_modules with npm
          command: npm install
      - save_cache:
          key: circleci-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
              - ./node_modules
      - run: 
          name: Build
          command: npm run build --prod 
      - run: 
          name: Running unit tests with karma
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
      - store_test_results:
          path: testresults