version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.3 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: Install node_modules with npm
          command: npm install
      - run: 
          name: Install karma-firefox-launcher
          command: npm install karma-firefox-launcher --save-dev
      - run: 
          name: Install karma-firefox-launcher
          command: npm install -g karma-cli
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      # - run:
      #     name: Install angularcli
      #     command: sudo npm install -g @angular/cli@latest
      #     environment: 
      #       NG_CLI_ANALYTICS:ci
      - run: 
          name: Running unit tests with karma
          command: sudo npm run test -- --no-watch --no-progress --browsers=Firefox